plugins {
    id "com.gradleup.shadow" version "9.4.2"
}

architectury {
    platformSetupLoomIde()
    loader("fabric")
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

loom {
    accessWidenerPath.set(file("src/main/resources/horseinboat.accesswidener"))
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

jar {
    archiveClassifier = "raw"
    archiveBaseName = "horseinboat-fabric"
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
}
