plugins {
	id "architectury-plugin" version "3.5-SNAPSHOT"
	id "dev.architectury.loom-no-remap" version "1.14-SNAPSHOT" apply false
}

architectury {
	minecraft = rootProject.minecraft_version
}

subprojects {
	apply plugin: "dev.architectury.loom-no-remap"

	loom {
		silentMojangMappingsLicense()
	}

	dependencies {
		minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
	}
}

allprojects {
	apply plugin: "java"
	apply plugin: "architectury-plugin"
	apply plugin: "maven-publish"

	base.archivesName = rootProject.archives_base_name
	version = rootProject.mod_version
	group = rootProject.maven_group

	tasks.withType(JavaCompile).configureEach() {
		options.encoding = "UTF-8"
		options.release = 25
	}

	java {
		withSourcesJar()
	}

	compileJava {
		options.compilerArgs +=	"-Xlint:-processing"
	}

	repositories {
		maven { url "https://maven.neoforged.net/releases/" }
		maven { url "https://maven.minecraftforge.net/" }
	}

}
